export const BLOGS_URL = 'blogs'
export const ASSETS_URL = 'assets'
export const INSTRUMENTS_URL = 'instruments'
export const PORTFOLIO_URL = 'portfolios'
export const PORTFOLIO_TRANSACTION_URL = 'portfolio_transactions'
export const PORTFOLIO_INSTRUMENTS_URL = 'portfolio_instruments'
export const DSE_SYNC_URL = '/api/dse/sync'
